import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_BRANCHES_LIST_START = `BRANCHES_LIST/GET/${START}`;
export const GET_BRANCHES_LIST_SUCCESS = `BRANCHES_LIST/GET/${SUCCESS}`;
export const GET_BRANCHES_LIST_FAIL = `BRANCHES_LIST/GET/${FAIL}`;

export const CREATE_BRANCH_START = `CREATE/BRANCH/${START}`;
export const CREATE_BRANCH_SUCCESS = `CREATE/BRANCH/${SUCCESS}`;
export const CREATE_BRANCH_FAIL = `CREATE/BRANCH/${FAIL}`;

export const EDIT_BRANCH_START = `EDIT/BRANCH/${START}`;
export const EDIT_BRANCH_SUCCESS = `EDIT/BRANCH/${SUCCESS}`;
export const EDIT_BRANCH_FAIL = `EDIT/BRANCH/${FAIL}`;

export const DELETE_BRANCH_START = `DELETE/BRANCH/${START}`;
export const DELETE_BRANCH_SUCCESS = `DELETE/BRANCH/${SUCCESS}`;
export const DELETE_BRANCH_FAIL = `DELETE/BRANCH/${FAIL}`;
