import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_CLIENTS_LIST_START = `CLIENTS_LIST/GET/${START}`;
export const GET_CLIENTS_LIST_SUCCESS = `CLIENTS_LIST/GET/${SUCCESS}`;
export const GET_CLIENTS_LIST_FAIL = `CLIENTS_LIST/GET/${FAIL}`;

export const CREATE_CLIENT_START = `CREATE/CLIENT/${START}`;
export const CREATE_CLIENT_SUCCESS = `CREATE/CLIENT/${SUCCESS}`;
export const CREATE_CLIENT_FAIL = `CREATE/CLIENT/${FAIL}`;

export const EDIT_CLIENT_START = `EDIT/CLIENT/${START}`;
export const EDIT_CLIENT_SUCCESS = `EDIT/CLIENT/${SUCCESS}`;
export const EDIT_CLIENT_FAIL = `EDIT/CLIENT/${FAIL}`;

export const DELETE_CLIENT_START = `DELETE/CLIENT/${START}`;
export const DELETE_CLIENT_SUCCESS = `DELETE/CLIENT/${SUCCESS}`;
export const DELETE_CLIENT_FAIL = `DELETE/CLIENT/${FAIL}`;
