import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_EMPLOYEES_LIST_START = `EMPLOYEES_LIST/GET/${START}`;
export const GET_EMPLOYEES_LIST_SUCCESS = `EMPLOYEES_LIST/GET/${SUCCESS}`;
export const GET_EMPLOYEES_LIST_FAIL = `EMPLOYEES_LIST/GET/${FAIL}`;

export const CREATE_EMPLOYEE_START = `CREATE/EMPLOYEE/${START}`;
export const CREATE_EMPLOYEE_SUCCESS = `CREATE/EMPLOYEE/${SUCCESS}`;
export const CREATE_EMPLOYEE_FAIL = `CREATE/EMPLOYEE/${FAIL}`;

export const EDIT_EMPLOYEE_START = `EDIT/EMPLOYEE/${START}`;
export const EDIT_EMPLOYEE_SUCCESS = `EDIT/EMPLOYEE/${SUCCESS}`;
export const EDIT_EMPLOYEE_FAIL = `EDIT/EMPLOYEE/${FAIL}`;

export const DELETE_EMPLOYEE_START = `DELETE/EMPLOYEE/${START}`;
export const DELETE_EMPLOYEE_SUCCESS = `DELETE/EMPLOYEE/${SUCCESS}`;
export const DELETE_EMPLOYEE_FAIL = `DELETE/EMPLOYEE/${FAIL}`;
