import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_MAILS_LIST_START = `MAILS_LIST/GET/${START}`;
export const GET_MAILS_LIST_SUCCESS = `MAILS_LIST/GET/${SUCCESS}`;
export const GET_MAILS_LIST_FAIL = `MAILS_LIST/GET/${FAIL}`;

export const CREATE_MAIL_START = `CREATE/MAIL/${START}`;
export const CREATE_MAIL_SUCCESS = `CREATE/MAIL/${SUCCESS}`;
export const CREATE_MAIL_FAIL = `CREATE/MAIL/${FAIL}`;
