import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_REVIEWS_START = `REVIEWS/GET/${START}`;
export const GET_REVIEWS_SUCCESS = `REVIEWS/GET/${SUCCESS}`;
export const GET_REVIEWS_FAIL = `REVIEWS/GET/${FAIL}`;

export const APPROVE_REVIEW_START = `REVIEW/APPROVE/${START}`;
export const APPROVE_REVIEW_SUCCESS = `REVIEW/APPROVE/${SUCCESS}`;
export const APPROVE_REVIEW_FAIL = `REVIEW/APPROVE/${FAIL}`;

export const REJECT_REVIEW_START = `REVIEW/REJECT/${START}`;
export const REJECT_REVIEW_SUCCESS = `REVIEW/REJECT/${SUCCESS}`;
export const REJECT_REVIEW_FAIL = `REVIEW/REJECT/${FAIL}`;
