import { START, SUCCESS, FAIL } from '../typeSettings';

export const GET_SERVICES_LIST_START = `SERVICES_LIST/GET/${START}`;
export const GET_SERVICES_LIST_SUCCESS = `SERVICES_LIST/GET/${SUCCESS}`;
export const GET_SERVICES_LIST_FAIL = `SERVICES_LIST/GET/${FAIL}`;

export const CREATE_SERVICE_START = `CREATE/SERVICE/${START}`;
export const CREATE_SERVICE_SUCCESS = `CREATE/SERVICE/${SUCCESS}`;
export const CREATE_SERVICE_FAIL = `CREATE/SERVICE/${FAIL}`;

export const EDIT_SERVICE_START = `EDIT/SERVICE/${START}`;
export const EDIT_SERVICE_SUCCESS = `EDIT/SERVICE/${SUCCESS}`;
export const EDIT_SERVICE_FAIL = `EDIT/SERVICE/${FAIL}`;

export const DELETE_SERVICE_START = `DELETE/SERVICE/${START}`;
export const DELETE_SERVICE_SUCCESS = `DELETE/SERVICE/${SUCCESS}`;
export const DELETE_SERVICE_FAIL = `DELETE/SERVICE/${FAIL}`;

export const GET_BRANCHES_LIST_START = `BRANCHES/LIST/GET/${START}`;
export const GET_BRANCHES_LIST_SUCCESS = `BRANCHES/LIST/GET/${SUCCESS}`;
export const GET_BRANCHES_LIST_FAIL = `BRANCHES/LIST/GET/${FAIL}`;
