import { START, SUCCESS, FAIL } from '../typeSettings';

export const SEND_MAIL_TO_SUPPORT_START = `AUTH/SEND_MAIL_TO_SUPPORT/${START}`;
export const SEND_MAIL_TO_SUPPORT_SUCCESS = `AUTH/SEND_MAIL_TO_SUPPORT/${SUCCESS}`;
export const SEND_MAIL_TO_SUPPORT_FAIL = `AUTH/SEND_MAIL_TO_SUPPORT/${FAIL}`;
